sonar.projectKey=PluckIt
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts,node_modules/**,coverage/**,dist/**
sonar.javascript.lcov.reportPaths=coverage/PluckIt.Client/lcov.info
sonar.typescript.tsconfigPath=tsconfig.app.json
